export const Cards = [
  {
    id: "1",
    cardNumber: "**** **** **** 1234",
    name: "John Doe",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "2",
    cardNumber: "**** **** **** 5678",
    name: "Jane Smith",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "3",
    cardNumber: "**** **** **** 8765",
    name: "Alice Johnson",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "4",
    cardNumber: "**** **** **** 4321",
    name: "Bob Anderson",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "5",
    cardNumber: "**** **** **** 9876",
    name: "Eve Williams",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "6",
    cardNumber: "**** **** **** 6543",
    name: "David Brown",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "7",
    cardNumber: "**** **** **** 7890",
    name: "Linda Davis",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "8",
    cardNumber: "**** **** **** 3456",
    name: "Michael Miller",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "9",
    cardNumber: "**** **** **** 2109",
    name: "Sophia Wilson",
    expiry: "12/24",
    cvv: "123",
  },
  {
    id: "10",
    cardNumber: "**** **** **** 6789",
    name: "Oliver Martinez",
    expiry: "12/24",
    cvv: "123",
  },
];
